
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Dua` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Dua
 * 
 */
export type DuaModel = runtime.Types.Result.DefaultSelection<Prisma.$DuaPayload>

export type AggregateDua = {
  _count: DuaCountAggregateOutputType | null
  _min: DuaMinAggregateOutputType | null
  _max: DuaMaxAggregateOutputType | null
}

export type DuaMinAggregateOutputType = {
  id: string | null
  titleBengali: string | null
  titleEnglish: string | null
  arabic: string | null
  transliteration: string | null
  bengali: string | null
  english: string | null
  tags: string | null
  category: string | null
  source: string | null
  times: string | null
  benefits: string | null
  fojilot: string | null
  rules: string | null
  context: string | null
  quranRef: string | null
  videoUrl: string | null
  articleUrl: string | null
  status: string | null
  rejectReason: string | null
  editToken: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DuaMaxAggregateOutputType = {
  id: string | null
  titleBengali: string | null
  titleEnglish: string | null
  arabic: string | null
  transliteration: string | null
  bengali: string | null
  english: string | null
  tags: string | null
  category: string | null
  source: string | null
  times: string | null
  benefits: string | null
  fojilot: string | null
  rules: string | null
  context: string | null
  quranRef: string | null
  videoUrl: string | null
  articleUrl: string | null
  status: string | null
  rejectReason: string | null
  editToken: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DuaCountAggregateOutputType = {
  id: number
  titleBengali: number
  titleEnglish: number
  arabic: number
  transliteration: number
  bengali: number
  english: number
  tags: number
  category: number
  source: number
  times: number
  benefits: number
  fojilot: number
  rules: number
  context: number
  quranRef: number
  videoUrl: number
  articleUrl: number
  segments: number
  status: number
  rejectReason: number
  editToken: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DuaMinAggregateInputType = {
  id?: true
  titleBengali?: true
  titleEnglish?: true
  arabic?: true
  transliteration?: true
  bengali?: true
  english?: true
  tags?: true
  category?: true
  source?: true
  times?: true
  benefits?: true
  fojilot?: true
  rules?: true
  context?: true
  quranRef?: true
  videoUrl?: true
  articleUrl?: true
  status?: true
  rejectReason?: true
  editToken?: true
  createdAt?: true
  updatedAt?: true
}

export type DuaMaxAggregateInputType = {
  id?: true
  titleBengali?: true
  titleEnglish?: true
  arabic?: true
  transliteration?: true
  bengali?: true
  english?: true
  tags?: true
  category?: true
  source?: true
  times?: true
  benefits?: true
  fojilot?: true
  rules?: true
  context?: true
  quranRef?: true
  videoUrl?: true
  articleUrl?: true
  status?: true
  rejectReason?: true
  editToken?: true
  createdAt?: true
  updatedAt?: true
}

export type DuaCountAggregateInputType = {
  id?: true
  titleBengali?: true
  titleEnglish?: true
  arabic?: true
  transliteration?: true
  bengali?: true
  english?: true
  tags?: true
  category?: true
  source?: true
  times?: true
  benefits?: true
  fojilot?: true
  rules?: true
  context?: true
  quranRef?: true
  videoUrl?: true
  articleUrl?: true
  segments?: true
  status?: true
  rejectReason?: true
  editToken?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DuaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Dua to aggregate.
   */
  where?: Prisma.DuaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Duas to fetch.
   */
  orderBy?: Prisma.DuaOrderByWithRelationInput | Prisma.DuaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DuaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Duas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Duas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Duas
  **/
  _count?: true | DuaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DuaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DuaMaxAggregateInputType
}

export type GetDuaAggregateType<T extends DuaAggregateArgs> = {
      [P in keyof T & keyof AggregateDua]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDua[P]>
    : Prisma.GetScalarType<T[P], AggregateDua[P]>
}




export type DuaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DuaWhereInput
  orderBy?: Prisma.DuaOrderByWithAggregationInput | Prisma.DuaOrderByWithAggregationInput[]
  by: Prisma.DuaScalarFieldEnum[] | Prisma.DuaScalarFieldEnum
  having?: Prisma.DuaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DuaCountAggregateInputType | true
  _min?: DuaMinAggregateInputType
  _max?: DuaMaxAggregateInputType
}

export type DuaGroupByOutputType = {
  id: string
  titleBengali: string
  titleEnglish: string | null
  arabic: string | null
  transliteration: string | null
  bengali: string
  english: string | null
  tags: string
  category: string | null
  source: string | null
  times: string | null
  benefits: string | null
  fojilot: string | null
  rules: string | null
  context: string | null
  quranRef: string | null
  videoUrl: string | null
  articleUrl: string | null
  segments: runtime.JsonValue | null
  status: string
  rejectReason: string | null
  editToken: string | null
  createdAt: Date
  updatedAt: Date
  _count: DuaCountAggregateOutputType | null
  _min: DuaMinAggregateOutputType | null
  _max: DuaMaxAggregateOutputType | null
}

type GetDuaGroupByPayload<T extends DuaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DuaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DuaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DuaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DuaGroupByOutputType[P]>
      }
    >
  >



export type DuaWhereInput = {
  AND?: Prisma.DuaWhereInput | Prisma.DuaWhereInput[]
  OR?: Prisma.DuaWhereInput[]
  NOT?: Prisma.DuaWhereInput | Prisma.DuaWhereInput[]
  id?: Prisma.StringFilter<"Dua"> | string
  titleBengali?: Prisma.StringFilter<"Dua"> | string
  titleEnglish?: Prisma.StringNullableFilter<"Dua"> | string | null
  arabic?: Prisma.StringNullableFilter<"Dua"> | string | null
  transliteration?: Prisma.StringNullableFilter<"Dua"> | string | null
  bengali?: Prisma.StringFilter<"Dua"> | string
  english?: Prisma.StringNullableFilter<"Dua"> | string | null
  tags?: Prisma.StringFilter<"Dua"> | string
  category?: Prisma.StringNullableFilter<"Dua"> | string | null
  source?: Prisma.StringNullableFilter<"Dua"> | string | null
  times?: Prisma.StringNullableFilter<"Dua"> | string | null
  benefits?: Prisma.StringNullableFilter<"Dua"> | string | null
  fojilot?: Prisma.StringNullableFilter<"Dua"> | string | null
  rules?: Prisma.StringNullableFilter<"Dua"> | string | null
  context?: Prisma.StringNullableFilter<"Dua"> | string | null
  quranRef?: Prisma.StringNullableFilter<"Dua"> | string | null
  videoUrl?: Prisma.StringNullableFilter<"Dua"> | string | null
  articleUrl?: Prisma.StringNullableFilter<"Dua"> | string | null
  segments?: Prisma.JsonNullableFilter<"Dua">
  status?: Prisma.StringFilter<"Dua"> | string
  rejectReason?: Prisma.StringNullableFilter<"Dua"> | string | null
  editToken?: Prisma.StringNullableFilter<"Dua"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Dua"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Dua"> | Date | string
}

export type DuaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  titleBengali?: Prisma.SortOrder
  titleEnglish?: Prisma.SortOrderInput | Prisma.SortOrder
  arabic?: Prisma.SortOrderInput | Prisma.SortOrder
  transliteration?: Prisma.SortOrderInput | Prisma.SortOrder
  bengali?: Prisma.SortOrder
  english?: Prisma.SortOrderInput | Prisma.SortOrder
  tags?: Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  times?: Prisma.SortOrderInput | Prisma.SortOrder
  benefits?: Prisma.SortOrderInput | Prisma.SortOrder
  fojilot?: Prisma.SortOrderInput | Prisma.SortOrder
  rules?: Prisma.SortOrderInput | Prisma.SortOrder
  context?: Prisma.SortOrderInput | Prisma.SortOrder
  quranRef?: Prisma.SortOrderInput | Prisma.SortOrder
  videoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  articleUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  segments?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectReason?: Prisma.SortOrderInput | Prisma.SortOrder
  editToken?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DuaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DuaWhereInput | Prisma.DuaWhereInput[]
  OR?: Prisma.DuaWhereInput[]
  NOT?: Prisma.DuaWhereInput | Prisma.DuaWhereInput[]
  titleBengali?: Prisma.StringFilter<"Dua"> | string
  titleEnglish?: Prisma.StringNullableFilter<"Dua"> | string | null
  arabic?: Prisma.StringNullableFilter<"Dua"> | string | null
  transliteration?: Prisma.StringNullableFilter<"Dua"> | string | null
  bengali?: Prisma.StringFilter<"Dua"> | string
  english?: Prisma.StringNullableFilter<"Dua"> | string | null
  tags?: Prisma.StringFilter<"Dua"> | string
  category?: Prisma.StringNullableFilter<"Dua"> | string | null
  source?: Prisma.StringNullableFilter<"Dua"> | string | null
  times?: Prisma.StringNullableFilter<"Dua"> | string | null
  benefits?: Prisma.StringNullableFilter<"Dua"> | string | null
  fojilot?: Prisma.StringNullableFilter<"Dua"> | string | null
  rules?: Prisma.StringNullableFilter<"Dua"> | string | null
  context?: Prisma.StringNullableFilter<"Dua"> | string | null
  quranRef?: Prisma.StringNullableFilter<"Dua"> | string | null
  videoUrl?: Prisma.StringNullableFilter<"Dua"> | string | null
  articleUrl?: Prisma.StringNullableFilter<"Dua"> | string | null
  segments?: Prisma.JsonNullableFilter<"Dua">
  status?: Prisma.StringFilter<"Dua"> | string
  rejectReason?: Prisma.StringNullableFilter<"Dua"> | string | null
  editToken?: Prisma.StringNullableFilter<"Dua"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Dua"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Dua"> | Date | string
}, "id">

export type DuaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  titleBengali?: Prisma.SortOrder
  titleEnglish?: Prisma.SortOrderInput | Prisma.SortOrder
  arabic?: Prisma.SortOrderInput | Prisma.SortOrder
  transliteration?: Prisma.SortOrderInput | Prisma.SortOrder
  bengali?: Prisma.SortOrder
  english?: Prisma.SortOrderInput | Prisma.SortOrder
  tags?: Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  times?: Prisma.SortOrderInput | Prisma.SortOrder
  benefits?: Prisma.SortOrderInput | Prisma.SortOrder
  fojilot?: Prisma.SortOrderInput | Prisma.SortOrder
  rules?: Prisma.SortOrderInput | Prisma.SortOrder
  context?: Prisma.SortOrderInput | Prisma.SortOrder
  quranRef?: Prisma.SortOrderInput | Prisma.SortOrder
  videoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  articleUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  segments?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectReason?: Prisma.SortOrderInput | Prisma.SortOrder
  editToken?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DuaCountOrderByAggregateInput
  _max?: Prisma.DuaMaxOrderByAggregateInput
  _min?: Prisma.DuaMinOrderByAggregateInput
}

export type DuaScalarWhereWithAggregatesInput = {
  AND?: Prisma.DuaScalarWhereWithAggregatesInput | Prisma.DuaScalarWhereWithAggregatesInput[]
  OR?: Prisma.DuaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DuaScalarWhereWithAggregatesInput | Prisma.DuaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Dua"> | string
  titleBengali?: Prisma.StringWithAggregatesFilter<"Dua"> | string
  titleEnglish?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  arabic?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  transliteration?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  bengali?: Prisma.StringWithAggregatesFilter<"Dua"> | string
  english?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  tags?: Prisma.StringWithAggregatesFilter<"Dua"> | string
  category?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  source?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  times?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  benefits?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  fojilot?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  rules?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  context?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  quranRef?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  videoUrl?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  articleUrl?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  segments?: Prisma.JsonNullableWithAggregatesFilter<"Dua">
  status?: Prisma.StringWithAggregatesFilter<"Dua"> | string
  rejectReason?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  editToken?: Prisma.StringNullableWithAggregatesFilter<"Dua"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Dua"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Dua"> | Date | string
}

export type DuaCreateInput = {
  id?: string
  titleBengali: string
  titleEnglish?: string | null
  arabic?: string | null
  transliteration?: string | null
  bengali: string
  english?: string | null
  tags: string
  category?: string | null
  source?: string | null
  times?: string | null
  benefits?: string | null
  fojilot?: string | null
  rules?: string | null
  context?: string | null
  quranRef?: string | null
  videoUrl?: string | null
  articleUrl?: string | null
  segments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: string
  rejectReason?: string | null
  editToken?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DuaUncheckedCreateInput = {
  id?: string
  titleBengali: string
  titleEnglish?: string | null
  arabic?: string | null
  transliteration?: string | null
  bengali: string
  english?: string | null
  tags: string
  category?: string | null
  source?: string | null
  times?: string | null
  benefits?: string | null
  fojilot?: string | null
  rules?: string | null
  context?: string | null
  quranRef?: string | null
  videoUrl?: string | null
  articleUrl?: string | null
  segments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: string
  rejectReason?: string | null
  editToken?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DuaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titleBengali?: Prisma.StringFieldUpdateOperationsInput | string
  titleEnglish?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arabic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transliteration?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bengali?: Prisma.StringFieldUpdateOperationsInput | string
  english?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  times?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefits?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fojilot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rules?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quranRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  articleUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  segments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  editToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DuaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titleBengali?: Prisma.StringFieldUpdateOperationsInput | string
  titleEnglish?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arabic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transliteration?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bengali?: Prisma.StringFieldUpdateOperationsInput | string
  english?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  times?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefits?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fojilot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rules?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quranRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  articleUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  segments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  editToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DuaCreateManyInput = {
  id?: string
  titleBengali: string
  titleEnglish?: string | null
  arabic?: string | null
  transliteration?: string | null
  bengali: string
  english?: string | null
  tags: string
  category?: string | null
  source?: string | null
  times?: string | null
  benefits?: string | null
  fojilot?: string | null
  rules?: string | null
  context?: string | null
  quranRef?: string | null
  videoUrl?: string | null
  articleUrl?: string | null
  segments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: string
  rejectReason?: string | null
  editToken?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DuaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titleBengali?: Prisma.StringFieldUpdateOperationsInput | string
  titleEnglish?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arabic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transliteration?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bengali?: Prisma.StringFieldUpdateOperationsInput | string
  english?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  times?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefits?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fojilot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rules?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quranRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  articleUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  segments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  editToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DuaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titleBengali?: Prisma.StringFieldUpdateOperationsInput | string
  titleEnglish?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arabic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transliteration?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bengali?: Prisma.StringFieldUpdateOperationsInput | string
  english?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  times?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefits?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fojilot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rules?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quranRef?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  articleUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  segments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rejectReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  editToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DuaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titleBengali?: Prisma.SortOrder
  titleEnglish?: Prisma.SortOrder
  arabic?: Prisma.SortOrder
  transliteration?: Prisma.SortOrder
  bengali?: Prisma.SortOrder
  english?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  category?: Prisma.SortOrder
  source?: Prisma.SortOrder
  times?: Prisma.SortOrder
  benefits?: Prisma.SortOrder
  fojilot?: Prisma.SortOrder
  rules?: Prisma.SortOrder
  context?: Prisma.SortOrder
  quranRef?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  articleUrl?: Prisma.SortOrder
  segments?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectReason?: Prisma.SortOrder
  editToken?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DuaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titleBengali?: Prisma.SortOrder
  titleEnglish?: Prisma.SortOrder
  arabic?: Prisma.SortOrder
  transliteration?: Prisma.SortOrder
  bengali?: Prisma.SortOrder
  english?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  category?: Prisma.SortOrder
  source?: Prisma.SortOrder
  times?: Prisma.SortOrder
  benefits?: Prisma.SortOrder
  fojilot?: Prisma.SortOrder
  rules?: Prisma.SortOrder
  context?: Prisma.SortOrder
  quranRef?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  articleUrl?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectReason?: Prisma.SortOrder
  editToken?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DuaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titleBengali?: Prisma.SortOrder
  titleEnglish?: Prisma.SortOrder
  arabic?: Prisma.SortOrder
  transliteration?: Prisma.SortOrder
  bengali?: Prisma.SortOrder
  english?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  category?: Prisma.SortOrder
  source?: Prisma.SortOrder
  times?: Prisma.SortOrder
  benefits?: Prisma.SortOrder
  fojilot?: Prisma.SortOrder
  rules?: Prisma.SortOrder
  context?: Prisma.SortOrder
  quranRef?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  articleUrl?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rejectReason?: Prisma.SortOrder
  editToken?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type DuaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titleBengali?: boolean
  titleEnglish?: boolean
  arabic?: boolean
  transliteration?: boolean
  bengali?: boolean
  english?: boolean
  tags?: boolean
  category?: boolean
  source?: boolean
  times?: boolean
  benefits?: boolean
  fojilot?: boolean
  rules?: boolean
  context?: boolean
  quranRef?: boolean
  videoUrl?: boolean
  articleUrl?: boolean
  segments?: boolean
  status?: boolean
  rejectReason?: boolean
  editToken?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dua"]>

export type DuaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titleBengali?: boolean
  titleEnglish?: boolean
  arabic?: boolean
  transliteration?: boolean
  bengali?: boolean
  english?: boolean
  tags?: boolean
  category?: boolean
  source?: boolean
  times?: boolean
  benefits?: boolean
  fojilot?: boolean
  rules?: boolean
  context?: boolean
  quranRef?: boolean
  videoUrl?: boolean
  articleUrl?: boolean
  segments?: boolean
  status?: boolean
  rejectReason?: boolean
  editToken?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dua"]>

export type DuaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titleBengali?: boolean
  titleEnglish?: boolean
  arabic?: boolean
  transliteration?: boolean
  bengali?: boolean
  english?: boolean
  tags?: boolean
  category?: boolean
  source?: boolean
  times?: boolean
  benefits?: boolean
  fojilot?: boolean
  rules?: boolean
  context?: boolean
  quranRef?: boolean
  videoUrl?: boolean
  articleUrl?: boolean
  segments?: boolean
  status?: boolean
  rejectReason?: boolean
  editToken?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dua"]>

export type DuaSelectScalar = {
  id?: boolean
  titleBengali?: boolean
  titleEnglish?: boolean
  arabic?: boolean
  transliteration?: boolean
  bengali?: boolean
  english?: boolean
  tags?: boolean
  category?: boolean
  source?: boolean
  times?: boolean
  benefits?: boolean
  fojilot?: boolean
  rules?: boolean
  context?: boolean
  quranRef?: boolean
  videoUrl?: boolean
  articleUrl?: boolean
  segments?: boolean
  status?: boolean
  rejectReason?: boolean
  editToken?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DuaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "titleBengali" | "titleEnglish" | "arabic" | "transliteration" | "bengali" | "english" | "tags" | "category" | "source" | "times" | "benefits" | "fojilot" | "rules" | "context" | "quranRef" | "videoUrl" | "articleUrl" | "segments" | "status" | "rejectReason" | "editToken" | "createdAt" | "updatedAt", ExtArgs["result"]["dua"]>

export type $DuaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Dua"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    titleBengali: string
    titleEnglish: string | null
    arabic: string | null
    transliteration: string | null
    bengali: string
    english: string | null
    tags: string
    category: string | null
    source: string | null
    times: string | null
    benefits: string | null
    fojilot: string | null
    rules: string | null
    context: string | null
    quranRef: string | null
    videoUrl: string | null
    articleUrl: string | null
    segments: runtime.JsonValue | null
    status: string
    rejectReason: string | null
    editToken: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dua"]>
  composites: {}
}

export type DuaGetPayload<S extends boolean | null | undefined | DuaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DuaPayload, S>

export type DuaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DuaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DuaCountAggregateInputType | true
  }

export interface DuaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Dua'], meta: { name: 'Dua' } }
  /**
   * Find zero or one Dua that matches the filter.
   * @param {DuaFindUniqueArgs} args - Arguments to find a Dua
   * @example
   * // Get one Dua
   * const dua = await prisma.dua.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DuaFindUniqueArgs>(args: Prisma.SelectSubset<T, DuaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DuaClient<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dua that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DuaFindUniqueOrThrowArgs} args - Arguments to find a Dua
   * @example
   * // Get one Dua
   * const dua = await prisma.dua.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DuaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DuaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DuaClient<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dua that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DuaFindFirstArgs} args - Arguments to find a Dua
   * @example
   * // Get one Dua
   * const dua = await prisma.dua.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DuaFindFirstArgs>(args?: Prisma.SelectSubset<T, DuaFindFirstArgs<ExtArgs>>): Prisma.Prisma__DuaClient<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dua that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DuaFindFirstOrThrowArgs} args - Arguments to find a Dua
   * @example
   * // Get one Dua
   * const dua = await prisma.dua.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DuaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DuaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DuaClient<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Duas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DuaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Duas
   * const duas = await prisma.dua.findMany()
   * 
   * // Get first 10 Duas
   * const duas = await prisma.dua.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const duaWithIdOnly = await prisma.dua.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DuaFindManyArgs>(args?: Prisma.SelectSubset<T, DuaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dua.
   * @param {DuaCreateArgs} args - Arguments to create a Dua.
   * @example
   * // Create one Dua
   * const Dua = await prisma.dua.create({
   *   data: {
   *     // ... data to create a Dua
   *   }
   * })
   * 
   */
  create<T extends DuaCreateArgs>(args: Prisma.SelectSubset<T, DuaCreateArgs<ExtArgs>>): Prisma.Prisma__DuaClient<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Duas.
   * @param {DuaCreateManyArgs} args - Arguments to create many Duas.
   * @example
   * // Create many Duas
   * const dua = await prisma.dua.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DuaCreateManyArgs>(args?: Prisma.SelectSubset<T, DuaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Duas and returns the data saved in the database.
   * @param {DuaCreateManyAndReturnArgs} args - Arguments to create many Duas.
   * @example
   * // Create many Duas
   * const dua = await prisma.dua.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Duas and only return the `id`
   * const duaWithIdOnly = await prisma.dua.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DuaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DuaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Dua.
   * @param {DuaDeleteArgs} args - Arguments to delete one Dua.
   * @example
   * // Delete one Dua
   * const Dua = await prisma.dua.delete({
   *   where: {
   *     // ... filter to delete one Dua
   *   }
   * })
   * 
   */
  delete<T extends DuaDeleteArgs>(args: Prisma.SelectSubset<T, DuaDeleteArgs<ExtArgs>>): Prisma.Prisma__DuaClient<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dua.
   * @param {DuaUpdateArgs} args - Arguments to update one Dua.
   * @example
   * // Update one Dua
   * const dua = await prisma.dua.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DuaUpdateArgs>(args: Prisma.SelectSubset<T, DuaUpdateArgs<ExtArgs>>): Prisma.Prisma__DuaClient<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Duas.
   * @param {DuaDeleteManyArgs} args - Arguments to filter Duas to delete.
   * @example
   * // Delete a few Duas
   * const { count } = await prisma.dua.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DuaDeleteManyArgs>(args?: Prisma.SelectSubset<T, DuaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Duas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DuaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Duas
   * const dua = await prisma.dua.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DuaUpdateManyArgs>(args: Prisma.SelectSubset<T, DuaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Duas and returns the data updated in the database.
   * @param {DuaUpdateManyAndReturnArgs} args - Arguments to update many Duas.
   * @example
   * // Update many Duas
   * const dua = await prisma.dua.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Duas and only return the `id`
   * const duaWithIdOnly = await prisma.dua.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DuaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DuaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Dua.
   * @param {DuaUpsertArgs} args - Arguments to update or create a Dua.
   * @example
   * // Update or create a Dua
   * const dua = await prisma.dua.upsert({
   *   create: {
   *     // ... data to create a Dua
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dua we want to update
   *   }
   * })
   */
  upsert<T extends DuaUpsertArgs>(args: Prisma.SelectSubset<T, DuaUpsertArgs<ExtArgs>>): Prisma.Prisma__DuaClient<runtime.Types.Result.GetResult<Prisma.$DuaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Duas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DuaCountArgs} args - Arguments to filter Duas to count.
   * @example
   * // Count the number of Duas
   * const count = await prisma.dua.count({
   *   where: {
   *     // ... the filter for the Duas we want to count
   *   }
   * })
  **/
  count<T extends DuaCountArgs>(
    args?: Prisma.Subset<T, DuaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DuaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dua.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DuaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DuaAggregateArgs>(args: Prisma.Subset<T, DuaAggregateArgs>): Prisma.PrismaPromise<GetDuaAggregateType<T>>

  /**
   * Group by Dua.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DuaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DuaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DuaGroupByArgs['orderBy'] }
      : { orderBy?: DuaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DuaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDuaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Dua model
 */
readonly fields: DuaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Dua.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DuaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Dua model
 */
export interface DuaFieldRefs {
  readonly id: Prisma.FieldRef<"Dua", 'String'>
  readonly titleBengali: Prisma.FieldRef<"Dua", 'String'>
  readonly titleEnglish: Prisma.FieldRef<"Dua", 'String'>
  readonly arabic: Prisma.FieldRef<"Dua", 'String'>
  readonly transliteration: Prisma.FieldRef<"Dua", 'String'>
  readonly bengali: Prisma.FieldRef<"Dua", 'String'>
  readonly english: Prisma.FieldRef<"Dua", 'String'>
  readonly tags: Prisma.FieldRef<"Dua", 'String'>
  readonly category: Prisma.FieldRef<"Dua", 'String'>
  readonly source: Prisma.FieldRef<"Dua", 'String'>
  readonly times: Prisma.FieldRef<"Dua", 'String'>
  readonly benefits: Prisma.FieldRef<"Dua", 'String'>
  readonly fojilot: Prisma.FieldRef<"Dua", 'String'>
  readonly rules: Prisma.FieldRef<"Dua", 'String'>
  readonly context: Prisma.FieldRef<"Dua", 'String'>
  readonly quranRef: Prisma.FieldRef<"Dua", 'String'>
  readonly videoUrl: Prisma.FieldRef<"Dua", 'String'>
  readonly articleUrl: Prisma.FieldRef<"Dua", 'String'>
  readonly segments: Prisma.FieldRef<"Dua", 'Json'>
  readonly status: Prisma.FieldRef<"Dua", 'String'>
  readonly rejectReason: Prisma.FieldRef<"Dua", 'String'>
  readonly editToken: Prisma.FieldRef<"Dua", 'String'>
  readonly createdAt: Prisma.FieldRef<"Dua", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Dua", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Dua findUnique
 */
export type DuaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * Filter, which Dua to fetch.
   */
  where: Prisma.DuaWhereUniqueInput
}

/**
 * Dua findUniqueOrThrow
 */
export type DuaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * Filter, which Dua to fetch.
   */
  where: Prisma.DuaWhereUniqueInput
}

/**
 * Dua findFirst
 */
export type DuaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * Filter, which Dua to fetch.
   */
  where?: Prisma.DuaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Duas to fetch.
   */
  orderBy?: Prisma.DuaOrderByWithRelationInput | Prisma.DuaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Duas.
   */
  cursor?: Prisma.DuaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Duas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Duas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Duas.
   */
  distinct?: Prisma.DuaScalarFieldEnum | Prisma.DuaScalarFieldEnum[]
}

/**
 * Dua findFirstOrThrow
 */
export type DuaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * Filter, which Dua to fetch.
   */
  where?: Prisma.DuaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Duas to fetch.
   */
  orderBy?: Prisma.DuaOrderByWithRelationInput | Prisma.DuaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Duas.
   */
  cursor?: Prisma.DuaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Duas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Duas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Duas.
   */
  distinct?: Prisma.DuaScalarFieldEnum | Prisma.DuaScalarFieldEnum[]
}

/**
 * Dua findMany
 */
export type DuaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * Filter, which Duas to fetch.
   */
  where?: Prisma.DuaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Duas to fetch.
   */
  orderBy?: Prisma.DuaOrderByWithRelationInput | Prisma.DuaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Duas.
   */
  cursor?: Prisma.DuaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Duas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Duas.
   */
  skip?: number
  distinct?: Prisma.DuaScalarFieldEnum | Prisma.DuaScalarFieldEnum[]
}

/**
 * Dua create
 */
export type DuaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * The data needed to create a Dua.
   */
  data: Prisma.XOR<Prisma.DuaCreateInput, Prisma.DuaUncheckedCreateInput>
}

/**
 * Dua createMany
 */
export type DuaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Duas.
   */
  data: Prisma.DuaCreateManyInput | Prisma.DuaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Dua createManyAndReturn
 */
export type DuaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * The data used to create many Duas.
   */
  data: Prisma.DuaCreateManyInput | Prisma.DuaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Dua update
 */
export type DuaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * The data needed to update a Dua.
   */
  data: Prisma.XOR<Prisma.DuaUpdateInput, Prisma.DuaUncheckedUpdateInput>
  /**
   * Choose, which Dua to update.
   */
  where: Prisma.DuaWhereUniqueInput
}

/**
 * Dua updateMany
 */
export type DuaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Duas.
   */
  data: Prisma.XOR<Prisma.DuaUpdateManyMutationInput, Prisma.DuaUncheckedUpdateManyInput>
  /**
   * Filter which Duas to update
   */
  where?: Prisma.DuaWhereInput
  /**
   * Limit how many Duas to update.
   */
  limit?: number
}

/**
 * Dua updateManyAndReturn
 */
export type DuaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * The data used to update Duas.
   */
  data: Prisma.XOR<Prisma.DuaUpdateManyMutationInput, Prisma.DuaUncheckedUpdateManyInput>
  /**
   * Filter which Duas to update
   */
  where?: Prisma.DuaWhereInput
  /**
   * Limit how many Duas to update.
   */
  limit?: number
}

/**
 * Dua upsert
 */
export type DuaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * The filter to search for the Dua to update in case it exists.
   */
  where: Prisma.DuaWhereUniqueInput
  /**
   * In case the Dua found by the `where` argument doesn't exist, create a new Dua with this data.
   */
  create: Prisma.XOR<Prisma.DuaCreateInput, Prisma.DuaUncheckedCreateInput>
  /**
   * In case the Dua was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DuaUpdateInput, Prisma.DuaUncheckedUpdateInput>
}

/**
 * Dua delete
 */
export type DuaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
  /**
   * Filter which Dua to delete.
   */
  where: Prisma.DuaWhereUniqueInput
}

/**
 * Dua deleteMany
 */
export type DuaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Duas to delete
   */
  where?: Prisma.DuaWhereInput
  /**
   * Limit how many Duas to delete.
   */
  limit?: number
}

/**
 * Dua without action
 */
export type DuaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dua
   */
  select?: Prisma.DuaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dua
   */
  omit?: Prisma.DuaOmit<ExtArgs> | null
}
